title: Quantum Computer Programming 2021-II
description: Universidad Nacional de Colombia, Bogot√°
sitename: Quantum Computer Programming
baseurl: '/qcp-2021-2'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
  - Gemfile.bak
  - .bundle
